name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: jodyhoonstarr/link-checker@master
      with:
        url: 'https://ledapplications.github.io/lehd-schema/lehd_shapefiles.html'
        honorRobotExclusions: true
        ignorePatterns: 'https://ledapplications.github.io/lehd-schema/lehd_shp_gc.zip,https://ledapplications.github.io/lehd-schema/lehd_shp_gs.zip'
        recursiveLinks: false
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
