name: Broken link check
on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Full Schema Link Check
      if: always()
      id: link-report-full-schema
      uses: jodyhoonstarr/link-checker@master
      with:
        # Required:
        url: 'https://ledapplications.github.io/lehd-schema/lehd_public_use_schema.html'
        # optional:
        ignorePatterns: ''
        recursiveLinks: false

    - name: Shapefiles Link Check
      if: always()
      id: link-report-shapefiles
      uses: jodyhoonstarr/link-checker@master
      with:
        url: 'https://ledapplications.github.io/lehd-schema/lehd_shapefiles.html'
        honorRobotExclusions: true
        ignorePatterns: 'https://ledapplications.github.io/lehd-schema/lehd_shp_*.zip'
        recursiveLinks: false
